name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest


    steps:

      - name: Deploy in EC2
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS }}  >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa
          chmod +x ~/.ssh/known_hosts


      - name: copying files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pwd
            sudo usermod -aG docker ${USER}
            su - ${USER}
            docker-compose up -d --build
            docker-compose up           
