name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  
          - name: Build the Docker image
            run: docker build . --file Dockerfile --tag junaidafzal2452/django
          - name: docker push
            run: |
              docker push junaidafzal2452/django

      - name: Deploy in EC2
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS }}  >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa
          chmod +x ~/.ssh/known_hosts


      - name: copying files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull junaidafzal2452/django
            docker-compose up
